trigger:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Inspect
    displayName: Inspect Build Tool Caches
    jobs:
      - job: Inspect
        displayName: Inspect Build Tool Caches
        steps:
          - task: GoTool@0
            inputs:
              version: '1.20.5'
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '18.x'
          - bash: |
              npm install --global pnpm
              npm install --global yarn

              npm config set cache=$(Pipeline.Workspace)/.npm
              pnpm config set store-dir $(Pipeline.Workspace)/.cache/pnpm-store
            displayName: Install additional tools
          - bash: cd docker/ && docker build . && cd ..
          - bash: cd gomod/ && go build && cd ..
          - bash: cd gradle/ && ./gradlew clean build && cd ..
          - bash: cd maven/ && ./mvnw clean package && cd ..
          - bash: cd npm/ && npm ci && cd ..
          - bash: cd pnpm/ && pnpm install && cd ..
          - bash: cd yarn/ && yarn install --frozen-lockfile && cd ..
          - bash: |
              echo "##[section]Docker"
              docker info
              echo "##[section]Go"
              go env
              echo "##[section]Gradle"
              cd gradle/ && ./gradlew projects --info && cd ..
              echo "##[section]Maven"
              cd maven/ && ./mvnw help:effective-settings && cd ..
              echo "##[section]NPM"
              npm config list
              echo "##[section]PNPM"
              echo "##[debug]Global"
              pnpm config list --global
              echo "##[debug]Local"
              pnpm config list
              echo "##[debug]Store"
              pnpm store path
              echo "##[section]Yarn"
              yarn config list
              echo "##[section]File/Folder overview"
              ls -la ${HOME}
              ls -la ${HOME}/.cache
